### ISSUE TITLE
Custom MQTT prefix makes the entities unavailables

### ISSUE THREAD

**Issue by palinf** [bieniu/ha-shellies-discovery#93] opened 2020-11-05 10:41 UTC
I had several devices which fail to be correctly inserted in HA while using custom MQTT prefix

The device was correctly recognised by the script and inserted in HA
but every entity failed to be something different than "unavailable" even after several restart.

custom MQTT prefix which cause problem |> renamed MQTT prefix which work
shellyswitch25: et1_living_interdouble1_E098068D4D59 |> et1_living_interd1_E098068D4D59
shellyswitch25: et1_living_interdouble2_8CAAB5058BC7 |> et1_living_interd2_8CAAB5058BC7
shellyem: et0_tableau_electrique_62127 |> et0_tableau_elec_62127
shellyswitch25: et0_couloir_interdoublehaut_B94647 |> et0_couloir_interddhaut_B94647
shelly1: et1_presence_temperature_E098068CCC48 |> et1_presence_temp_plafond_E098068CCC48

Sorry but by the time of the mistake I did investigate the code and the logs.
I hope this will be obvious issue for you.

**Comment by bieniu** [comment] 2020-11-05 10:49
Honestly, I don't really understand what causes the problem and what you've changed to fix the problem.

**Comment by palinf** [comment] 2020-11-05 10:59
On this device,
shellyswitch25: et1_living_interdouble1_E098068D4D59 |> et1_living_interd1_E098068D4D59
I changed the mqtt prefix from this original naming convention: 
et1_living_interdouble1_E098068D4D59 
to 
et1_living_interd1_E098068D4D59 in order for the entities to be recognised.

I did not change anything in the code. This was strange as 18 others devices with the same original convention worked flawlessly.

**Comment by bieniu** [comment] 2020-11-05 11:40
Maybe the devices have a limit on the length of the MQTT prefix (or lenghth of the topic) and if it's too long, they don't use the correct topics (without the entire prefix)?

**Comment by palinf** [comment] 2020-11-06 19:32
It is not a length problem as other devices works well.
Also the device is recognised in HA.
The information goes through MQTT and probably the first steps of shellies_discovery.py
I was thinking more about some condition for detecting the type or so within the script.
If it does not ring a bell then close this ticket. I renamed the devices and all is fine. Next time it happens I will dig it.
Thanks

**Comment by alberanid** [comment] 2020-11-20 20:36
Hi,
I have a similar experience, but I've still not tried resetting my custom prefix.

What happens: after 12 hours (expire_after value) some entities became unavailable.

Devices: Shelly door/window 2 and leakage sensors.

Talking about the dw2 sensors, mine have firmware 20200818-120407/v1.8.2@36539b0b

What I see in the Home Assistant logs:
```
2020-11-20 19:29:18 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: binary_sensor shellydw2-kitchen-opening, sending update
2020-11-20 19:29:18 INFO (MainThread) [homeassistant.components.mqtt] Got update for entity with hash: ('binary_sensor', 'shellydw2-kitchen-opening') '{'name': 'Shelly Door/Window 2 kitchen Opening', 'state_topic': 'shellies/shellydw2-kitchen/sensor/state', 'unique_id': 'shellydw2-kitchen-opening', 'qos': 0, 'device': {'identifiers': ['40f5202d9a85'], 'name': 'Shelly Door/Window 2 kitchen', 'model': 'Shelly Door/Window 2', 'sw_version': '20200818-120407/v1.8.2@36539b0b', 'manufacturer': 'Allterco Robotics'}, 'payload_on': 'open', 'payload_off': 'close', 'expire_after': 43200, 'device_class': 'opening', 'platform': 'mqtt'}'
2020-11-20 19:29:18 INFO (MainThread) [homeassistant.components.mqtt] Ignoring unchanged update for: binary_sensor.kitchen_window_opening
```

What I see if I subscribe to the **shellies/shellydw2-kitchen/#** topic in the last few hours:
```
shellies/shellydw2-kitchen/online true
shellies/shellydw2-kitchen/announce {"id":"shellydw2-kitchen","model":"SHDW-2","mac":"40F5202D9A85","ip":"10.42.20.60","new_fw":false,"fw_ver":"20200818-120407/v1.8.2@36539b0b"}
shellies/shellydw2-kitchen/sensor/tilt 0
shellies/shellydw2-kitchen/sensor/vibration 0
shellies/shellydw2-kitchen/sensor/temperature 21.20
shellies/shellydw2-kitchen/sensor/lux 31
shellies/shellydw2-kitchen/sensor/illumination twilight
shellies/shellydw2-kitchen/sensor/battery 100
shellies/shellydw2-kitchen/sensor/error 0
shellies/shellydw2-kitchen/sensor/act_reasons ["sensor"]
shellies/shellydw2-kitchen/online false
shellies/shellydw2-kitchen/online true
shellies/shellydw2-kitchen/announce {"id":"shellydw2-kitchen","model":"SHDW-2","mac":"40F5202D9A85","ip":"10.42.20.60","new_fw":false,"fw_ver":"20200818-120407/v1.8.2@36539b0b"}
shellies/shellydw2-kitchen/sensor/tilt 0
shellies/shellydw2-kitchen/sensor/vibration 0
shellies/shellydw2-kitchen/sensor/temperature 21.20
shellies/shellydw2-kitchen/sensor/lux 0
shellies/shellydw2-kitchen/sensor/illumination dark
shellies/shellydw2-kitchen/sensor/battery 100
shellies/shellydw2-kitchen/sensor/error 0
shellies/shellydw2-kitchen/sensor/act_reasons ["sensor"]
shellies/shellydw2-kitchen/online false
```

As you can see, the **shellies/shellydw2-kitchen/sensor/** topic is always missing.

Am I correct to assume a bug in the firmware, or is there something else I am missing?

Let me know if I can do more tests or help debugging this issue.

**Comment by bieniu** [comment] 2020-11-20 21:55
Show me debug log for `python_script` component.
What is the `sleep_mode.period` value for the device?

**Comment by alberanid** [comment] 2020-11-20 22:44
the `python_script` logs:
```
2020-11-20 19:29:18 INFO (SyncWorker_0) [homeassistant.components.python_script] Executing shellies_discovery.py: {'id': 'shellydw2-kitchen', 'mac': '40F5202D9A85', 'fw_ver': '20200818-120407/v1.8.2@36539b0b', 'model': 'SHDW-2'}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] id: shellydw2-kitchen, mac: 40f5202d9a85, fw_ver: 20200818-120407/v1.8.2@36539b0b, model: SHDW-2
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/sensor/shellydw2-kitchen-lux/config {"name": "Shelly Door/Window 2 kitchen Lux", "stat_t": "~sensor/lux", "frc_upd": "False", "uniq_id": "shellydw2-kitchen-lux", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "json_attr_t": "~sensor/illumination", "json_attr_tpl": "{{{'illumination':value}|tojson}}", "unit_of_meas": "lx", "dev_cla": "illuminance", "val_tpl": "{{value|float|round}}", "exp_aft": 43200}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/sensor/shellydw2-kitchen-battery/config {"name": "Shelly Door/Window 2 kitchen Battery", "stat_t": "~sensor/battery", "frc_upd": "False", "uniq_id": "shellydw2-kitchen-battery", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "unit_of_meas": "%", "dev_cla": "battery", "val_tpl": "{{value|float|round}}", "exp_aft": 43200}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/sensor/shellydw2-kitchen-tilt/config {"name": "Shelly Door/Window 2 kitchen Tilt", "stat_t": "~sensor/tilt", "frc_upd": "False", "uniq_id": "shellydw2-kitchen-tilt", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "unit_of_meas": "°", "val_tpl": "{{value|float}}", "exp_aft": 43200}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/sensor/shellydw2-kitchen-temperature/config {"name": "Shelly Door/Window 2 kitchen Temperature", "stat_t": "~sensor/temperature", "frc_upd": "False", "uniq_id": "shellydw2-kitchen-temperature", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "unit_of_meas": "°C", "dev_cla": "temperature", "val_tpl": "{{value|float|round(1)}}", "exp_aft": 43200}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/binary_sensor/shellydw2-kitchen-opening/config {"name": "Shelly Door/Window 2 kitchen Opening", "stat_t": "~sensor/state", "uniq_id": "shellydw2-kitchen-opening", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "pl_on": "open", "pl_off": "close", "exp_aft": 43200, "dev_cla": "opening"}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/binary_sensor/shellydw2-kitchen-vibration/config {"name": "Shelly Door/Window 2 kitchen Vibration", "stat_t": "~sensor/vibration", "uniq_id": "shellydw2-kitchen-vibration", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "pl_on": "1", "pl_off": "0", "exp_aft": 43200, "dev_cla": "vibration"}
2020-11-20 19:29:18 DEBUG (SyncWorker_0) [homeassistant.components.python_script.shellies_discovery.py] Sending to MQTT broker: homeassistant/binary_sensor/shellydw2-kitchen-firmware-update/config {"name": "Shelly Door/Window 2 kitchen Firmware Update", "stat_t": "~announce", "uniq_id": "shellydw2-kitchen-firmware-update", "qos": 0, "dev": {"ids": ["40f5202d9a85"], "name": "Shelly Door/Window 2 kitchen", "mdl": "Shelly Door/Window 2", "sw": "20200818-120407/v1.8.2@36539b0b", "mf": "Allterco Robotics"}, "~": "shellies/shellydw2-kitchen/", "val_tpl": "{%if value_json.new_fw==true%}ON{%else%}OFF{%endif%}"}
```

Regarding the device: `device.sleep_mode` is true (as always) and `sleep_mode` is:
```
  "sleep_mode": {
    "period": 6,
    "unit": "h"
  },
```

Another thing that bothers me of this devices is that, despite SNTP is enabled and set to time.google.com, the `time` and `unixtime` keys are always empty and 0, respectively. I understand that they don't have an rtc, but at least when they are discoverable I would assume they'd update their clock.

Thanks for your support.

**Comment by bieniu** [comment] 2020-11-21 10:17
So it seems the device doesn't send `shellies/shellydw2-kitchen/sensor/state` periodically. I can't do anything with that, this is device firmware problem. You can increase `expire_after` as a workaround.


> the `time` and `unixtime` keys are always empty and 0, respectively

It's device issue, ask Shelly support.

**Comment by alberanid** [comment] 2020-11-23 20:26
you are right, I'll open a ticket.

I've also tested @palinf solution (avoid using a custom MQTT topic), but also that didn't help.

Thanks for your support.

**Comment by bieniu** [comment] 2020-11-23 20:34
Maybe you can try with Shelly firmware 1.9_rc3?

**Comment by alberanid** [comment] 2020-11-23 20:52
Strange thing, I'm offered an older release of 1.8.2 as beta firmware.

Where can I get 1.9_rc3?

I don't see it even on http://archive.shelly-faq.de/ (by the way, is that
site legit?)

Thanks!


Il lun 23 nov 2020, 21:34 Maciej Bieniek <notifications@github.com> ha
scritto:

**Comment by bieniu** [comment] 2020-11-23 21:10
> Where can I get 1.9_rc3?

https://repo.shelly.cloud/files/firmware

**Comment by alberanid** [comment] 2020-12-06 12:28
To close this issue, at least for me, I received an official reply from their support team:

> The state is sent only on change. It's inappropriate for the door state to be sent periodically with the other parameters, because it has only two states. Also, many users use automation based on the door state, so if you receive the same door state on the periodic update, it would not be correct (it means for example that the door is closed, but it was closed also before sending the periodic update). I hope you understand why this is intentionally made like that.

So, this is intentional.

**Comment by bieniu** [comment] 2020-12-07 08:17
I added `force_update` to `opening` sensors and increased the default values of `expire_after`. Please test https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.35.0

**Comment by alberanid** [comment] 2020-12-07 20:11
cool! Updated to 0.35.1 via HACS.

Pardon my ignorance: do I have to re-configure my devices for it to take effect? In that case, I have some new devices that should be delivered in the next 2 weeks, and I can try it with those.

Another question: the documentation says that "the script requires you to set the value of 12h for sleep_mode.period"; my devices have a sleep_mode.period of 6h. Is it okay or do I have to increase it?

Thanks!

**Comment by bieniu** [comment] 2020-12-07 20:18
> Pardon my ignorance: do I have to re-configure my devices for it to take effect?

You have to run `announce` automation or restart HA.

> Another question: the documentation says that "the script requires you to set the value of 12h for sleep_mode.period"; my devices have a sleep_mode.period of 6h. Is it okay or do I have to increase it?

If `sleep_period` is other than 12h you have to configure manually `expire_after` for that device. I recommend `expire_after = 1.2 * sleep_period * 60 * 60`

**Comment by alberanid** [comment] 2020-12-12 17:03
Still no luck.

I think I need to clarify some context, since it's possible that I'm missing something about how HA is supposed to work.

## Setup

* **devices with the problem**: Shelly door/window 2 and Shelly flood (both battery-powered)
* **device configuration**: Cloud disabled, MQTT enabled (usually with custom topic, but this is not the problem); sleep_mode.period set to 12h (tested also with lower values)
* **device firmware**: latest stable (1.8.2 and 1.9.0)
* **WiFi signal**: excellent
* **networking**: all my devices and HA are on the same VLAN
* **Shellies Discovery**: version 0.35.4
* **Home Assistant**: 0.118.5
* **other integrations**: I've tried with and without ShellyForHass and the default HA Shelly integration

## Problem

After 12 hours the `_opening` entities (mapped from the `/state` MQTT topic) representing the last action done by the sensor (door/window open/closed) turns to **unavailable**.

Once the door/window is open (or closed) again, the new state is sent correctly.

All other entities of the device (tilt, temperature, etc.) are seen correctly and they never goes to the unavailable state.

**NOTE**: this is a problem on the Home Assistant UI, where I see this, and not a problem of functionality: if I configure correctly my automations (to ignore transitions to "unavailable"), they work okay:

![office-unavailable](https://user-images.githubusercontent.com/222857/101989885-9ca00280-3ca3-11eb-9379-4d1a8d595004.jpg)

## MQTT observation

I can see the other topics from the device (temperature, tilt, ...) sent periodically, but not `state`.

## Shelly support answer

They say this is done by design, since they do not want to trigger again a "open door" automation.

## Questions

Here, I'm not sure were the problem lies.

Is HA supposed to only rely only on periodic updates from MQTT to keep the entity from becoming unavailable? 

Is HA supposed to also use CoAP (using the default integration or ShellyForHass, maybe?) to decide if a device is available or not?

Am I missing something else entirely? :-)

Thanks for your support!

**Comment by bieniu** [comment] 2020-12-12 21:04
> Is HA supposed to only rely only on periodic updates from MQTT to keep the entity from becoming unavailable?

Yes, for battery powerwd devices we assume that the entity is available when we have their status periodically updated.

> Is HA supposed to also use CoAP (using the default integration or ShellyForHass, maybe?) to decide if a device is available or not?

MQTT integration uses MQTT data, CoAP integration uses CoAP data.

> Am I missing something else entirely? :-)

I think that only possible workaround is increase value of expire_after.

**Closed** 2020-12-13 12:02 UTC

**Comment by alberanid** [comment] 2020-12-13 14:28
> I think that only possible workaround is increase value of expire_after.

Pardon if I reply to a closed issue (@palinf: I'm okay with closing this one, but in general if you are no longer interested in an issue you can just unsubscribe and leave it open until the assignee closes it).

Just a quick question: do you know what's the easiest way to do it?

Do you think that changing your script like this:
```
EXPIRE_AFTER_FOR_BATTERY_POWERED = int(data.get('expire_after_for_battery_powered', 1.2 * 12 * 60 * 60)) # 1.2 * 12 h
EXPIRE_AFTER_FOR_AC_POWERED = int(data.get('expire_after_for_ac_powered', 2.2 * 10 * 60))  # 2.2 * 10 min
```

and adding `expire_after_for_battery_powered: 604800` in the **data_template** of the automation could work?

Thanks

**Comment by bieniu** [comment] 2020-12-13 14:40
The script supports `expire_after` for battery powered devices. Just use it with your problematic device.

**Comment by bieniu** [comment] 2020-12-27 13:19
https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.35.6
