### ISSUE TITLE
Shelly Duo light status doesn't update correctly

### ISSUE THREAD

**Issue by metalloid14** [bieniu/ha-shellies-discovery#87] opened 2020-10-06 23:15 UTC
Hi,
I've been using the Shellies Discovery Script for some days now and it works great. But, I do have an issue with all of my Shelly Duo lights. I can turn them on, but I cannot have the right status on the entity on HA. 
Looking at the debug info, I can see that the light is on (and I can go and see for myself that it is really on), but in the HA entity status, it is not. In all the debug info bellow, the status of the bulb in HA is off.
Debug info example :
```
shellies/living_room_side_light_1/light/0/status
10 most recently received message(s):
Received 12:03:59 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:04:29 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:04:59 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:05:29 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:05:59 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:06:29 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:06:57 AM
QoS: 0
Payload: ison: true
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 73
white: 0
temp: 0
Received 12:06:58 AM
QoS: 0
Payload: ison: false
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:06:59 AM
QoS: 0
Payload: ison: false
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 75
white: 0
temp: 0
Received 12:07:03 AM
QoS: 0
Payload: ison: false
has_timer: false
timer_started: 0
timer_duration: 0
timer_remaining: 0
brightness: 72
white: 0
temp: 0
```

These last ones, in HA I switched it on and off quite fast, and the bulb did turned off (I checked), and so the status is correct... but only when is not on.
Am I doing something wrong? Could it be because I changed the entity name?
Thanks for all your work!
Jorge

**Comment by metalloid14** [comment] 2020-10-06 23:21
Also, found this in HA log (when I tried to turn on the light in HA. It did turn on, but the status is off):
2020-10-07 00:20:00 ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'shellies/living_room_side_light_1/light/0/status': '{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"brightness":1,"white":0,"temp":0}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 35, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_template.py", line 249, in state_received
    self._templates[
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render_with_possible_json_value
    return self._compiled.render(variables).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

**Comment by bieniu** [comment] 2020-10-07 06:55
Your bulb sends `temp: 0`, according to the documentation, the `temp` value should be 2700-6500 https://shelly-api-docs.shelly.cloud/#shelly-duo-mqtt

**Comment by metalloid14** [comment] 2020-10-07 23:32
Hi @bieniu,
I think The firmware is te latest:
“Current version: 20200827-065050/v1.8.3@4a8bc427 
You have latest version of your device!”

**Comment by bieniu** [comment] 2020-10-08 07:10
Please give me the value range of the `temp` parameter.

**Comment by bieniu** [comment] 2020-10-08 10:24
This is a bug in the Shelly firmware. When `white = 0` device sends `temp = 0` but it should `temp = 2700`. Please report to the Shelly support.

**Comment by bieniu** [comment] 2020-10-08 10:38
Closed via https://github.com/bieniu/ha-shellies-discovery/releases/tag/0.30.5

**Closed by bieniu** 2020-10-08 10:38 UTC
Labels: question

**Comment by bieniu** [comment] 2020-10-16 12:03
@metalloid14 I received this message from the Shelly development team.
"I reproduced the issue with FW version 1.8.3, but with the latest master build, I think it's no longer there.
It could be a side effect, can you verify if the issue is still existing with the latest master build?
Link: http://repo.shelly.cloud/firmware/test/SHBDUO-1.zip"
Can you check if the problem is on this test firmware? When `white` is `0`, `temp` should be `2700`, not `0`.
